# inventory.yml

all:
  hosts:
    testserver1:
      host: 3.83.238.253
      user: ubuntu
      ssh_private_key_file: ./pair-ansible-challenge.pem

    testserver2:
          host: 52.7.160.19
          user: ubuntu
          ssh_private_key_file: ./pair-ansible-challenge.pem
